# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_wallpaper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import bg_rc
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import QPixmap, QPainter
from PyQt5 import QtCore, QtGui, QtWidgets


class MyWidget(QtWidgets.QWidget):
    def __init__(self, bg):
        super().__init__()
        self.bg = bg

    def paintEvent(self, event):
        painter = QPainter(self)
        pixmap = QPixmap(self.bg)  # 替换为您的图片路径
        painter.drawPixmap(self.rect(), pixmap)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-image: url(:/bg/bg2.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 19, 803, 584))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.screen1 = MyWidget(r"D:\project\壁纸管理\bg.png")
        self.screen1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screen1.setAutoFillBackground(False)
        # self.screen1.setStyleSheet("border-image: url(:/bg/bg.png);")
        self.screen1.setObjectName("screen1")
        self.label = QtWidgets.QLabel(self.screen1)
        self.label.setGeometry(QtCore.QRect(20, 20, 160, 90))
        self.label.setStyleSheet("border-image: url(:/bg/bg.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.screen1)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 160, 90))
        self.label_2.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.screen1)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 160, 90))
        self.label_3.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.screen1)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 160, 90))
        self.label_7.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.screen1)
        self.label_8.setGeometry(QtCore.QRect(200, 130, 160, 90))
        self.label_8.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.screen1)
        self.label_9.setGeometry(QtCore.QRect(380, 130, 160, 90))
        self.label_9.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.screen1)
        self.label_10.setGeometry(QtCore.QRect(200, 240, 160, 90))
        self.label_10.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.screen1)
        self.label_11.setGeometry(QtCore.QRect(380, 240, 160, 90))
        self.label_11.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.screen1)
        self.label_12.setGeometry(QtCore.QRect(20, 240, 160, 90))
        self.label_12.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.screen1)
        self.label_13.setGeometry(QtCore.QRect(200, 350, 160, 90))
        self.label_13.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.screen1)
        self.label_14.setGeometry(QtCore.QRect(380, 350, 160, 90))
        self.label_14.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.screen1)
        self.label_15.setGeometry(QtCore.QRect(20, 350, 160, 90))
        self.label_15.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.screen1)
        self.label_16.setGeometry(QtCore.QRect(200, 460, 160, 90))
        self.label_16.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.screen1)
        self.label_17.setGeometry(QtCore.QRect(380, 460, 160, 90))
        self.label_17.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.screen1)
        self.label_18.setGeometry(QtCore.QRect(20, 460, 160, 90))
        self.label_18.setStyleSheet("border-image: url(:/bg/bg2.png);")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/bg/bg.png"))
        self.label_18.setObjectName("label_18")
        self.line = QtWidgets.QFrame(self.screen1)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(560, 0, 2, 551))
        self.line.setStyleSheet(" ")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.screen1, "")
        self.screen2 = QtWidgets.QWidget()
        self.screen2.setObjectName("screen2")
        self.tabWidget.addTab(self.screen2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.screen1), _translate("MainWindow", "屏幕1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.screen2), _translate("MainWindow", "屏幕2"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
